// ─────────────────────────────────────────────────────────────────────────────
// Your profile — a real page, reached from the account menu in the top-right.
//
// This was a cramped modal launched from the sidebar footer. It is a page now
// (Daniel, 2026-09-02) for the same reason Settings and Notifications are:
// these are the boring, occasional, personal screens, and they deserve room to
// breathe and a URL you can link someone to — not a dialog stacked over
// whatever you happened to be looking at.
//
// Deliberately still small. This is the one place a person edits THEMSELVES.
// User management, roles and tab grants stay in /admin/team behind super-admin.
//
// The photo goes through POST /api/admin/uploads/image — the generic uploader
// the page-block editor already uses. It re-encodes to webp, caps the size and
// marks the object public, then hands back an `/objects/...` path. That path
// is the ONLY shape PATCH /api/auth/me will store: an arbitrary absolute URL
// would turn every staff list into a tracking pixel for whoever owns the host.
// ─────────────────────────────────────────────────────────────────────────────
import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Camera, Loader2, Trash2, User } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";

type Me = {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  /** Absent entirely on a server that predates the avatar column. */
  avatarUrl?: string | null;
  role: string;
};

const MAX_BYTES = 10 * 1024 * 1024;

export default function ProfilePage() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const fileRef = useRef<HTMLInputElement>(null);

  const { data: me, isLoading } = useQuery<Me>({ queryKey: ["/api/auth/me"] });

  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [uploading, setUploading] = useState(false);
  // Seed the fields once the user arrives, and again if they change under us
  // (View As, another tab) — but never while the person is mid-edit, or their
  // typing would be overwritten by a background refetch.
  const [seeded, setSeeded] = useState(false);

  useEffect(() => {
    if (!seeded && me) {
      setFirstName(me.firstName ?? "");
      setLastName(me.lastName ?? "");
      setSeeded(true);
    }
  }, [me, seeded]);

  const save = useMutation({
    mutationFn: (patch: Partial<Pick<Me, "firstName" | "lastName" | "avatarUrl">>) =>
      apiRequest("PATCH", "/api/auth/me", patch),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["/api/auth/me"] });
    },
    onError: (e: any) =>
      toast({
        title: "Couldn't save",
        description: e?.message ?? "Something went wrong.",
        variant: "destructive",
      }),
  });

  const initials = me ? `${me.firstName?.[0] ?? ""}${me.lastName?.[0] ?? ""}` || "?" : "?";

  const onFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    // Reset immediately so choosing the SAME file again still fires onChange.
    e.target.value = "";
    if (!file) return;
    if (!file.type.startsWith("image/")) {
      toast({ title: "That's not an image", description: "Pick a JPG, PNG or WEBP.", variant: "destructive" });
      return;
    }
    if (file.size > MAX_BYTES) {
      toast({ title: "Image too big", description: "Maximum 10MB.", variant: "destructive" });
      return;
    }

    setUploading(true);
    try {
      const form = new FormData();
      form.append("file", file);
      // Raw fetch, not apiRequest: the multipart boundary must be generated by
      // the browser, and a JSON Content-Type header here yields a body multer
      // cannot parse.
      const res = await fetch("/api/admin/uploads/image", {
        method: "POST",
        body: form,
        credentials: "include",
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body?.message || `Upload failed (${res.status})`);
      }
      const { url } = (await res.json()) as { url: string };
      await save.mutateAsync({ avatarUrl: url });
      toast({ title: "Photo updated" });
    } catch (err: any) {
      toast({
        title: "Upload failed",
        description: err?.message ?? "Couldn't upload that photo.",
        variant: "destructive",
      });
    } finally {
      setUploading(false);
    }
  };

  const removePhoto = async () => {
    await save.mutateAsync({ avatarUrl: null });
    toast({ title: "Photo removed" });
  };

  const saveName = async () => {
    if (!firstName.trim()) {
      toast({ title: "First name can't be blank", variant: "destructive" });
      return;
    }
    await save.mutateAsync({ firstName: firstName.trim(), lastName: lastName.trim() });
    toast({ title: "Profile saved" });
  };

  const dirty = !!me && (firstName !== (me.firstName ?? "") || lastName !== (me.lastName ?? ""));

  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-8 space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight flex items-center gap-2">
          <User className="w-5 h-5 text-muted-foreground" />
          Your profile
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Your name and photo, as the rest of the team sees them.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Photo</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-wrap items-center gap-5">
          <div className="relative">
            <Avatar className="h-20 w-20">
              {me?.avatarUrl ? <AvatarImage src={me.avatarUrl} alt="" /> : null}
              <AvatarFallback className="bg-primary text-primary-foreground text-lg font-semibold">
                {initials}
              </AvatarFallback>
            </Avatar>
            {uploading && (
              <div className="absolute inset-0 rounded-full bg-background/70 flex items-center justify-center">
                <Loader2 className="w-5 h-5 animate-spin text-primary" />
              </div>
            )}
          </div>
          <div className="flex flex-col gap-2">
            <div className="flex flex-wrap gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={() => fileRef.current?.click()}
                disabled={uploading}
                data-testid="button-change-photo"
              >
                <Camera className="w-4 h-4 mr-2" />
                Change photo
              </Button>
              {me?.avatarUrl && (
                <Button
                  type="button"
                  variant="ghost"
                  onClick={removePhoto}
                  disabled={uploading || save.isPending}
                  className="text-destructive hover:text-destructive"
                  data-testid="button-remove-photo"
                >
                  <Trash2 className="w-4 h-4 mr-2" />
                  Remove
                </Button>
              )}
            </div>
            <p className="text-xs text-muted-foreground">JPG, PNG or WEBP. Up to 10MB.</p>
          </div>
          <input
            ref={fileRef}
            type="file"
            accept="image/*"
            className="hidden"
            onChange={onFile}
            data-testid="input-photo"
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Name</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="firstName">First name</Label>
              <Input
                id="firstName"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                disabled={isLoading}
                data-testid="input-first-name"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="lastName">Last name</Label>
              <Input
                id="lastName"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                disabled={isLoading}
                data-testid="input-last-name"
              />
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Button
              onClick={saveName}
              disabled={!dirty || save.isPending}
              data-testid="button-save-profile"
            >
              {save.isPending && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              Save changes
            </Button>
            {dirty && <span className="text-xs text-muted-foreground">Unsaved changes</span>}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Account</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          <div className="flex justify-between gap-4">
            <span className="text-muted-foreground">Email</span>
            <span className="font-medium truncate" data-testid="text-profile-email">
              {me?.email ?? "—"}
            </span>
          </div>
          <div className="flex justify-between gap-4">
            <span className="text-muted-foreground">Role</span>
            <span className="font-medium capitalize">{me?.role?.replace(/_/g, " ") ?? "—"}</span>
          </div>
          <p className="text-xs text-muted-foreground pt-1">
            Your email address and role are set by an administrator and can't be changed here.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
