// "Your profile" — the staff member's own name and photo, on desktop.
//
// Reached by clicking your avatar in the sidebar footer. Deliberately tiny:
// this is the one place a person edits THEMSELVES, and it must not grow into
// a second admin panel. User management, roles and tab grants stay in
// /admin/team behind super-admin, where they belong.
//
// The photo goes through POST /api/admin/uploads/image — the generic uploader
// the page-block editor already uses. It re-encodes to webp, caps the size and
// marks the object public, then hands back an `/objects/...` path. That path
// is the ONLY shape PATCH /api/auth/me will store: an arbitrary absolute URL
// would turn every staff list into a tracking pixel for whoever owns the host.

import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Camera, Loader2, Trash2 } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";

type Me = {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  /** Absent entirely on a server that predates the avatar column. */
  avatarUrl?: string | null;
  role: string;
};

const MAX_BYTES = 10 * 1024 * 1024;

export function ProfileDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (v: boolean) => void }) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const fileRef = useRef<HTMLInputElement>(null);

  const { data: me } = useQuery<Me>({ queryKey: ["/api/auth/me"] });

  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [uploading, setUploading] = useState(false);

  // Re-seed the fields whenever the dialog opens, so an abandoned edit from
  // last time never silently reappears as the value about to be saved.
  useEffect(() => {
    if (open && me) {
      setFirstName(me.firstName ?? "");
      setLastName(me.lastName ?? "");
    }
  }, [open, me]);

  const save = useMutation({
    mutationFn: (patch: Partial<Pick<Me, "firstName" | "lastName" | "avatarUrl">>) =>
      apiRequest("PATCH", "/api/auth/me", patch),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["/api/auth/me"] });
    },
    onError: (e: any) => toast({ title: "Couldn't save", description: e?.message ?? "Something went wrong.", variant: "destructive" }),
  });

  const initials = me ? `${me.firstName?.[0] ?? ""}${me.lastName?.[0] ?? ""}` : "?";

  const pickFile = () => fileRef.current?.click();

  const onFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    // Reset immediately so choosing the SAME file again still fires onChange.
    e.target.value = "";
    if (!file) return;
    if (!file.type.startsWith("image/")) {
      toast({ title: "That's not an image", description: "Pick a JPG, PNG or WEBP.", variant: "destructive" });
      return;
    }
    if (file.size > MAX_BYTES) {
      toast({ title: "Image too big", description: "Maximum 10MB.", variant: "destructive" });
      return;
    }

    setUploading(true);
    try {
      const form = new FormData();
      form.append("file", file);
      // Raw fetch, not apiRequest: the multipart boundary must be generated by
      // the browser, and a JSON Content-Type header here yields a body multer
      // cannot parse.
      const res = await fetch("/api/admin/uploads/image", { method: "POST", body: form, credentials: "include" });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body?.message || `Upload failed (${res.status})`);
      }
      const { url } = (await res.json()) as { url: string };
      await save.mutateAsync({ avatarUrl: url });
      toast({ title: "Photo updated" });
    } catch (err: any) {
      toast({ title: "Upload failed", description: err?.message ?? "Couldn't upload that photo.", variant: "destructive" });
    } finally {
      setUploading(false);
    }
  };

  const removePhoto = async () => {
    await save.mutateAsync({ avatarUrl: null });
    toast({ title: "Photo removed" });
  };

  const saveName = async () => {
    if (!firstName.trim()) {
      toast({ title: "First name can't be blank", variant: "destructive" });
      return;
    }
    await save.mutateAsync({ firstName: firstName.trim(), lastName: lastName.trim() });
    toast({ title: "Profile saved" });
    onOpenChange(false);
  };

  const dirty = !!me && (firstName !== (me.firstName ?? "") || lastName !== (me.lastName ?? ""));

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[420px]">
        <DialogHeader>
          <DialogTitle>Your profile</DialogTitle>
          <DialogDescription>Your name and photo, as the rest of the team sees them.</DialogDescription>
        </DialogHeader>

        <div className="flex items-center gap-4 py-2">
          <div className="relative">
            <Avatar className="h-20 w-20">
              {me?.avatarUrl ? <AvatarImage src={me.avatarUrl} alt="" /> : null}
              <AvatarFallback className="bg-gradient-to-br from-blue-500 to-blue-700 text-white text-xl font-semibold">
                {initials || "?"}
              </AvatarFallback>
            </Avatar>
            <button
              type="button"
              onClick={pickFile}
              disabled={uploading}
              className="absolute -bottom-1 -right-1 h-8 w-8 rounded-full bg-blue-600 text-white flex items-center justify-center border-2 border-background hover:bg-blue-500 disabled:opacity-60"
              title="Change photo"
              data-testid="button-change-photo"
            >
              {uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Camera className="h-4 w-4" />}
            </button>
          </div>

          <div className="flex flex-col gap-2">
            <Button type="button" variant="secondary" size="sm" onClick={pickFile} disabled={uploading}>
              {uploading ? "Uploading…" : me?.avatarUrl ? "Change photo" : "Upload a photo"}
            </Button>
            {me?.avatarUrl ? (
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="text-destructive hover:text-destructive"
                onClick={removePhoto}
                disabled={save.isPending || uploading}
                data-testid="button-remove-photo"
              >
                <Trash2 className="h-3.5 w-3.5 mr-1.5" />
                Remove
              </Button>
            ) : null}
          </div>
        </div>

        <input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={onFile} />

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-1.5">
            <Label htmlFor="profile-first">First name</Label>
            <Input
              id="profile-first"
              value={firstName}
              onChange={(e) => setFirstName(e.target.value)}
              maxLength={100}
              data-testid="input-first-name"
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="profile-last">Last name</Label>
            <Input
              id="profile-last"
              value={lastName}
              onChange={(e) => setLastName(e.target.value)}
              maxLength={100}
              data-testid="input-last-name"
            />
          </div>
        </div>

        <p className="text-xs text-muted-foreground">
          {me?.email} · {me?.role?.replace(/_/g, " ")}
        </p>

        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button onClick={saveName} disabled={!dirty || save.isPending} data-testid="button-save-profile">
            {save.isPending ? "Saving…" : "Save"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
